CC = gcc
CFLAGS = -Wall -lm 
out = lab1
source = lab1.c Funciones.c
objects = $(source:.c=.o)
depends = .depends
headers = Funciones.h

$(out): $(objects)

	$(CC) -o $@ $^ $(CFLAGS) -L .
$(objects):
	$(CC) -c $*.c
$(depends): $(source) $(headers)
	@$(CC) -MM $(source) > $@
clean:
	rm -f $(objects) $(out) $(depends)
.PHONY:clean
sinclude $(depends)